main/urls.py
from django.urls import path
from . import views
from main.decorators import check_recaptcha

urlpatterns = [
    path('', check_recaptcha(views.index), name='index'),
    path('about', check_recaptcha(views.about), name='about'),
    path('developers', check_recaptcha(views.area), name='area'),
    path('amenities', check_recaptcha(views.amenities), name='amenities'),
    path('gallery', check_recaptcha(views.gallery), name='gallery'),
    path('listings', check_recaptcha(views.available_units), name='available_units'),
    path('contacts', check_recaptcha(views.contacts), name='contacts'),
    path('privacy-policy', check_recaptcha(views.privacy), name='privacy-policy'),
    path('terms', check_recaptcha(views.terms), name='terms'),
    ]

townhouses/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls'))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

main/models.py
from django.db import models


class Gallery(models.Model):
    gallery_img = models.ImageField(upload_to='images/')


class Listing(models.Model):
    FLOOR = models.CharField(null=True, max_length=20)
    UNIT_FORM = models.CharField(null=True, max_length=20)
    UNIT_TYPE = models.CharField(null=True, max_length=300)
    BEDROOMS = models.CharField(null=True, max_length=5)
    BATHROOMS = models.CharField(null=True, max_length=5)
    UNIT = models.CharField(null=True, max_length=20)
    INTERIOR = models.CharField(null=True, max_length=50)
    TERRACE = models.CharField(null=True, max_length=50)
    TOTAL = models.CharField(null=True, max_length=50)
    PRICE = models.CharField(null=True, max_length=50)
    FLOOR_PLANE = models.FileField(upload_to='floor_plane/', blank=True)


class FeedBack(models.Model):
    user_type_choices = (
        ('yes', 'Yes'),
        ('no', 'No'),
    )

    first_name = models.CharField(max_length=150, blank=True, verbose_name='First name')
    last_name = models.CharField(max_length=150, blank=True, verbose_name='Last name')
    phone = models.CharField(max_length=150, blank=True, verbose_name='Phone')
    email = models.EmailField(blank=True, verbose_name='Email')
    agent_type = models.CharField(max_length=150,  blank=True, choices=user_type_choices, verbose_name='Is a realtor')
    message = models.TextField(blank=True, verbose_name='message')
    date_creation = models.DateTimeField(auto_now_add=True, blank=True, null=True, verbose_name='Date creation')

    def __str__(self):
        return self.first_name

    class Meta:
        verbose_name = 'Item'
        verbose_name_plural = 'Feedbacks'


class BookPoint(models.Model):
    user_type_choices = (
        ('yes', 'Yes'),
        ('no', 'No'),
    )

    time_choices = (
        ('09:00', '09:00'),
        ('10:00', '10:00'),
        ('11:00', '11:00'),
        ('12:00', '12:00'),
        ('13:00', '13:00'),
        ('14:00', '14:00'),
        ('15:00', '15:00'),
        ('16:00', '16:00'),
        ('17:00', '17:00'),
        ('18:00', '18:00'),
        ('19:00', '19:00'),
        ('20:00', '20:00'),
    )

    first_name = models.CharField(max_length=150, blank=True, verbose_name='First name')
    last_name = models.CharField(max_length=150, blank=True, verbose_name='Last name')
    phone = models.CharField(max_length=150, blank=True, verbose_name='Phone')
    email = models.EmailField(blank=True, verbose_name='Email')
    agent_type = models.CharField(max_length=150,  blank=True, choices=user_type_choices, verbose_name='Is a realtor')
    message = models.TextField(blank=True, verbose_name='message')
    date = models.CharField(max_length=50, blank=True, verbose_name='Date and time')
    date_creation = models.DateTimeField(auto_now_add=True, blank=True, null=True, verbose_name='Date creation')

    def __str__(self):
        return self.first_name

    class Meta:
        verbose_name = 'Item'
        verbose_name_plural = 'Book an appointments'

main/forms.py
from django import forms
from main.models import FeedBack, BookPoint


class ContactForm(forms.ModelForm):
    class Meta:
        model = FeedBack
        fields = '__all__'


class BookPointForm(forms.ModelForm):
    class Meta:
        model = BookPoint
        fields = '__all__'

main/views.py
from django.shortcuts import render
from .models import Gallery, Listing
from django.db.models import Q


def index(request):
    return render(request, 'main/pages/index.html')


def about(request):
    return render(request, 'main/pages/about.html')


def area(request):
    return render(request, 'main/pages/area.html')


def amenities(request):
    return render(request, 'main/pages/amenities.html')


def gallery(request):
    gal_img = Gallery.objects.all()
    return render(request, 'main/pages/gallery.html', context={'gal_img': gal_img})


def available_units(request):
    return render(request, 'main/pages/available_units.html')


def contacts(request):
    return render(request, 'main/pages/contacts.html')


def privacy(request):
    return render(request, 'main/pages/privacy-policy.html')


def terms(request):
    return render(request, 'main/pages/terms.html')

templates/main/includes/modals/modal_book_an_appointment.html
{% load crispy_forms_tags %}

<!-- Modal Book an appointment -->
<div class="modal fade" id="exampleModal2" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered">
        <div class="modal-content rounded-0">
            <div class="modal-header">
                <h5 class="modal-title" style="color: #455694" id="exampleModalLabel">Book an appointment</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body text-center">
                <form method="post" id="bookpoint_form" class="contact-form">
                    {% csrf_token %}
                    <div class="row g-2 my-font-contact" style="opacity: 0.8;!important;">
                        <div>
                            <div class="form-floating mb-3">
                                <div id="div_id_first_name">
                                    <input type="text" name="first_name" id="id_first_name" class="my-form font-regular"
                                           placeholder="First name*" required>
                                </div>
                            </div>
                            <div class="form-floating mb-3">
                                <div id="div_id_last_name">
                                    <input type="text" name="last_name" id="id_last_name" class="my-form font-regular"
                                           placeholder="Last name*" required>
                                </div>
                            </div>
                            <div class="form-floating mb-3">
                                <div id="div_id_phone">
                                    <input type="tel" name="phone" id="id_phone" class="my-form font-regular phone"
                                           placeholder="Your phone*" required>
                                </div>
                            </div>
                            <div class="form-floating mb-3">
                                <div id="div_id_email">
                                    <input type="text" id="id_email" name="email" class="my-form font-regular"
                                           placeholder="Your email*" required>
                                </div>
                            </div>
                            <div class="form-floating mb-3">
                                <div>
                                    <select class="my-form font-regular" style="color: #848383" name="agent_type"
                                            aria-label="Default select example" required>
                                        <option class="font-regular" style="color: #848383" value="">Are you a realtor?*
                                        </option>
                                        <option class="my-sel font-regular" value="yes">Yes</option>
                                        <option class="my-sel font-regular" value="no">No</option>
                                    </select>
                                </div>
                            </div>
                            <div class="mb-3">
                                <textarea name="message" id="id_message" style="height: 50px"
                                          class="my-form font-regular rounded-0" rows="3"
                                          placeholder="Message"></textarea>
                            </div>
                            <div class="mb-3">
                                <div id="div_id_date">
                                    <input type="datetime-local" id="id_date" name="date" class="my-form font-regular"
                                           style="color: #848383"
                                           placeholder="Select date and time" required>
                                </div>
                            </div>
                            <div class="mb-3 form-group g-recaptcha"
                                 data-sitekey="6LdEDmIfAAAAAG0pduuigfo5zmBDCBCLbujFGpbi"></div>
                            <button name="bookpoint_form_btn" type="submit"
                                    class="but-empty mb-3">Send
                            </button>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>

templates/main/includes/modals/modal_sign_up.html
{% load crispy_forms_tags %}
{% load static %}

<!-- Modal Sign Up -->
<div class="modal fade" id="sign_up" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered">
        <div class="modal-content rounded-0">
            <div class="modal-header">
                <h5 class="modal-title" style="color: #455694" id="exampleModalLabel">Sign up</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body text-center">
                <form method="post" id="contact_form" class="contact-form my-font">
                    {% csrf_token %}
                    <div class="row g-2 my-font-contact" style="opacity: 0.8;!important;">
                        <div>
                            <div class="form-floating mb-3">
                                <div id="div_id_first_name">
                                    <input type="text" name="first_name" id="id_first_name" class="my-form font-regular"
                                           placeholder="First name*" required>
                                </div>
                            </div>
                            <div class="form-floating mb-3">
                                <div id="div_id_last_name">
                                    <input type="text" name="last_name" id="id_last_name" class="my-form font-regular"
                                           placeholder="Last name*" required>
                                </div>
                            </div>
                            <div class="form-floating mb-3">
                                <div id="div_id_phone">
                                    <input type="tel" name="phone" id="id_phone" class="my-form font-regular phone"
                                           placeholder="Your phone*" required>
                                </div>
                            </div>
                            <div class="form-floating mb-3">
                                <div id="div_id_email">
                                    <input type="text" id="id_email" name="email" class="my-form font-regular"
                                           placeholder="Your email*" required>
                                </div>
                            </div>
                            <div class="form-floating mb-3">
                                <div>
                                    <select class="my-form font-regular" style="color: #848383" name="agent_type"
                                            aria-label="Default select example" required>
                                        <option class="font-regular" style="color: #8b8b8b" value="">Are you a realtor?*
                                        </option>
                                        <option class="my-sel" value="yes">Yes</option>
                                        <option class="my-sel" value="no">No</option>
                                    </select>
                                </div>
                            </div>
                            <div class="mb-3">
                                <textarea name="message" id="id_message" style="height: 50px"
                                          class="my-form font-regular rounded-0" rows="3"
                                          placeholder="Message"></textarea>
                            </div>
                            <div class="mb-3 form-group g-recaptcha"
                                 data-sitekey="6LdEDmIfAAAAAG0pduuigfo5zmBDCBCLbujFGpbi"></div>
                            <button name="contact_form_btn" type="submit"
                                    class="but-empty mb-3">Send
                            </button>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>

templates/main/includes/modals/modal_write_to_us.html
{% load crispy_forms_tags %}

<!-- Modal Write to us -->
<div class="modal fade" id="exampleModal1" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered">
        <div class="modal-content rounded-0">
            <div class="modal-header">
                <h5 class="modal-title" style="color: #455694" id="exampleModalLabel">Contact us</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body text-center">
                <form method="post" id="contact_form" class="contact-form my-font">
                    {% csrf_token %}
                    <div class="row g-2 my-font-contact" style="opacity: 0.8;!important;">
                        <div>
                            <div class="form-floating mb-3">
                                <div id="div_id_first_name">
                                    <input type="text" name="first_name" id="id_first_name" class="my-form font-regular"
                                           placeholder="First name*" required>
                                </div>
                            </div>
                            <div class="form-floating mb-3">
                                <div id="div_id_last_name">
                                    <input type="text" name="last_name" id="id_last_name" class="my-form font-regular"
                                           placeholder="Last name*" required>
                                </div>
                            </div>
                            <div class="form-floating mb-3">
                                <div id="div_id_phone">
                                    <input type="tel" name="phone" id="id_phone" class="my-form font-regular phone"
                                           placeholder="Your phone*" required>
                                </div>
                            </div>
                            <div class="form-floating mb-3">
                                <div id="div_id_email">
                                    <input type="text" id="id_email" name="email" class="my-form font-regular"
                                           placeholder="Your email*" required>
                                </div>
                            </div>
                            <div class="form-floating mb-3">
                                <div>
                                    <select class="my-form font-regular" style="color: #848383" name="agent_type"
                                            aria-label="Default select example" required>
                                        <option class="font-regular" style="color: #8b8b8b" value="">Are you a realtor?*
                                        </option>
                                        <option class="my-sel" value="yes">Yes</option>
                                        <option class="my-sel" value="no">No</option>
                                    </select>
                                </div>
                            </div>
                            <div class="mb-3">
                                <textarea name="message" id="id_message" style="height: 50px"
                                          class="my-form font-regular rounded-0" rows="3"
                                          placeholder="Message"></textarea>
                            </div>
                            <div class="mb-3 form-group g-recaptcha"
                                 data-sitekey="6LdEDmIfAAAAAG0pduuigfo5zmBDCBCLbujFGpbi"></div>
                            <button name="contact_form_btn" type="submit"
                                    class="but-empty mb-3">Send
                            </button>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>

templates/main/includes/other_head.html
{% load static %}

<!-- Yandex.Metrika counter -->
<script type="text/javascript">
    (function (m, e, t, r, i, k, a) {
        m[i] = m[i] || function () {
            (m[i].a = m[i].a || []).push(arguments)
        };
        m[i].l = 1 * new Date();
        k = e.createElement(t), a = e.getElementsByTagName(t)[0], k.async = 1, k.src = r, a.parentNode.insertBefore(k, a)
    })
    (window, document, "script", "https://mc.yandex.ru/metrika/tag.js", "ym");

    ym(88163694, "init", {
        clickmap: true,
        trackLinks: true,
        accurateTrackBounce: true
    });
</script>
<noscript>
    <div><img src="https://mc.yandex.ru/watch/88163694" style="position:absolute; left:-9999px;" alt=""/></div>
</noscript>
<!-- /Yandex.Metrika counter -->


<!-- Global site tag (gtag.js) - Google Analytics -->
<script async src="https://www.googletagmanager.com/gtag/js?id=G-T58LPF3JWT"></script>
<script>
    window.dataLayer = window.dataLayer || [];

    function gtag() {
        dataLayer.push(arguments);
    }

    gtag('js', new Date());

    gtag('config', 'G-T58LPF3JWT');
</script>

templates/main/layout/header.html
{% load static %}

<nav class="header navbar navbar-expand-lg navbar-light shadow fixed-top" style="background-color: white">
    <div class="container">
        <a href="{% url 'index' %}" class="me-auto me-lg-0">
            <img style="height: 58px; width: auto;" src="{% static 'main/img/icons/logo.png' %}" alt="">
        </a>
        <button class="navbar-toggler btn-mobile-nav" type="button" data-bs-toggle="collapse"
                data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent"
                aria-expanded="false"
                aria-label="Toggle navigation"><span class="navbar-toggler-icon"></span></button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav ms-auto mb-2 mb-lg-0">
                <li class="nav-item"><a class="nav-link font-gt-all font-index" href="{% url 'index' %}">Home</a>
                </li>
                <li class="nav-item"><a class="nav-link font-gt-all font-about" href="{% url 'about' %}">About</a>
                </li>
                <li class="nav-item"><a class="nav-link font-gt-all font-area" href="{% url 'area' %}">Area</a>
                </li>
                <li class="nav-item"><a class="nav-link font-gt-all font-amenities" href="{% url 'amenities' %}">Amenities</a>
                </li>
                <li class="nav-item"><a class="nav-link font-gt-all font-gallery" href="{% url 'gallery' %}">Gallery</a>
                </li>
                <li class="nav-item"><a class="nav-link font-gt-all font-available_units" href="{% url 'available_units' %}">Available
                    Units</a></li>
                <li class="nav-item"><a class="nav-link font-gt-all font-contact" href="{% url 'contacts' %}">Contacts</a>
                </li>
            </ul>
        </div>
    </div>
</nav>

templates/main/pages/contacts.html
{% extends 'main/layout/layout.html' %}
{% load static %}
{% load crispy_forms_tags %}

{% block title %}Contacts{% endblock %}

{% block top %}
    <style>
        .footer-contacts-none {
            display: none;
        }

        .footer-contacts-block {
            display: block;
        }

        .my-mb-0 {
            margin-bottom: 0 !important;
        }

        .font-contact {
            font-weight: 800;
            color: #455694 !important;
            text-decoration: underline #f5c269;
            text-decoration-thickness: 3px;
        }

    </style>
{% endblock %}

{% block content %}
    <section class="container bg-color block-contacts" style="padding-top: 67px;!important;">
        <div class="row bg-color align-content-center d-flex justify-content-start">
            <div class="col-lg-6">
                <div class="row align-content-center ">
                    <div class="col-lg-8">
                        <h2 class="fs-2 text-center mb-4">Contacts</h2>
                    </div>
                    <div class="col-lg-12 mb-4">
                        <h3 class="fs-5 fw-bolder"><img class="img-svg icons-style"
                                                        src="{% static 'main/img/icons/location.svg' %}"
                                                        alt="Location"> Location:</h3>
                        <p class="fs-5" style="padding-left: 29px;">2850 NE 32nd St, Fort Lauderdale, FL 33306</p>
                    </div>
                    <div class="col-lg-12 mb-4">
                        <h5 class="fs-5 fw-bolder"><img class="img-svg icons-style"
                                                        src="{% static 'main/img/icons/email.svg' %}"
                                                        alt="Email"> Email:</h5>
                        <p class="fs-5" style="padding-left: 29px;"><a href="mailto:info@residencesbaccarat.com"
                                                                       class="my-link">info@residencesbaccarat.com</a>
                        </p>
                    </div>
                    <div class="col-lg-12 mb-4">
                        <h5 class="fs-5 fw-bolder"><img class="img-svg icons-style"
                                                        src="{% static 'main/img/icons/call.svg' %}"
                                                        alt="Call"> Call:</h5>
                        <p class="fs-5" style="padding-left: 29px;"><a href="tel:+1 (305) 306-7370"
                                                                       class="my-link">+1 (305) 306-7370</a></p>
                    </div>
                    <div class="col-lg-6 mb-4">
                        <div class="messengers-icons">
                            <h5 class="fs-5 fw-bolder"><img class="img-svg icons-style"
                                                            src="{% static 'main/img/icons/social.svg' %}"
                                                            alt="Email"> Social:</h5>
                            <div style="padding-left: 29px;">
                                <div class="mb-2">
                                    <a class="fs-5 icons-style whatsapp mx-1" href="https://wa.me/13053067370"
                                       style="text-decoration: none;">
                                        <img class="img-svg icons-style whatsapp"
                                             src="{% static 'main/img/icons/whatsapp.svg' %}"
                                             alt="whatsapp">
                                    </a>
                                    <a class="fs-5 icons-style telegram mx-1" href="https://wa.me/13053067370"
                                       style="text-decoration: none;">
                                        <img class="img-svg icons-style telegram"
                                             src="{% static 'main/img/icons/telegram.svg' %}"
                                             alt="whatsapp">
                                    </a>
                                    <a class="fs-5 icons-style instagram mx-1" href="https://wa.me/13053067370"
                                       style="text-decoration: none;">
                                        <img class="img-svg icons-style instagram"
                                             src="{% static 'main/img/icons/instagram.svg' %}"
                                             alt="whatsapp">
                                    </a>
                                    <a class="fs-5 icons-style facebook mx-1" href="https://wa.me/13053067370"
                                       style="text-decoration: none;">
                                        <img class="img-svg icons-style facebook"
                                             src="{% static 'main/img/icons/facebook.svg' %}"
                                             alt="whatsapp">
                                    </a>
                                </div>

                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-lg-6">
                <h2 class="fs-2 mb-4 text-center">Write to us</h2>
                <form method="post" id="contact_form" class="contact-form my-font">
                    {% csrf_token %}
                    <div class="row g-2 my-font-contact" style="opacity: 0.8 !important;">
                        <div>
                            <div class="form-floating mb-3">
                                <div id="div_id_first_name">
                                    <input type="text" name="first_name" id="id_first_name"
                                           class="my-form form-bg-color font-regular"
                                           placeholder="First name*" required>
                                </div>
                            </div>
                            <div class="form-floating mb-3">
                                <div id="div_id_last_name">
                                    <input type="text" name="last_name" id="id_last_name"
                                           class="my-form form-bg-color font-regular"
                                           placeholder="Last name*" required>
                                </div>
                            </div>
                            <div class="form-floating mb-3">
                                <div id="div_id_phone">
                                    <input type="tel" name="phone" id="id_phone"
                                           class="my-form form-bg-color font-regular phone"
                                           placeholder="Your phone*" required>
                                </div>
                            </div>
                            <div class="form-floating mb-3">
                                <div id="div_id_email">
                                    <input type="text" id="id_email" name="email"
                                           class="my-form form-bg-color font-regular"
                                           placeholder="Your email*" required>
                                </div>
                            </div>
                            <div class="form-floating mb-3">
                                <div>
                                    <select class="my-form form-bg-color font-regular" style="color: #848383"
                                            name="agent_type"
                                            aria-label="Default select example" required>
                                        <option class="font-regular" style="color: #8b8b8b" value="">Are you a realtor?*
                                        </option>
                                        <option class="my-sel" value="yes">Yes</option>
                                        <option class="my-sel" value="no">No</option>
                                    </select>
                                </div>
                            </div>
                            <div class="mb-3">
                                <textarea name="message" id="id_message" style="height: 50px"
                                          class="my-form form-bg-color font-regular rounded-0" rows="3"
                                          placeholder="Message"></textarea>
                            </div>
                            <div class="mb-3 form-group g-recaptcha"
                                 data-sitekey="6LdEDmIfAAAAAG0pduuigfo5zmBDCBCLbujFGpbi"></div>
                            <button name="contact_form_btn" type="submit"
                                    class="but-empty mb-5">Send
                            </button>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </section>

        <section class="container pt-5 pb-5">
        <div class="row">
            <div class="col-lg-12 order-lg-3 text-center">
                <a data-bs-toggle="modal"
                   data-bs-target="#exampleModal2"
                   class="but-blue text-uppercase">
                    Book an appointment
                </a>
            </div>
        </div>
    </section>

    <section class="container-fluid my-back mt-0 mx-0 shadow">
        <div class="row" style="height: 50vh">
            <div class="col-lg-12 px-0">
                <div id='map' style="height: 100%; width: 100%"></div>
            </div>
        </div>
    </section>
{% endblock %}

templates/main/pages/gallery.html
{% extends 'main/layout/layout.html' %}
{% load static %}


{% block title %}Gallery{% endblock %}

{% block top %}
    <style>
        .font-gallery {
            font-weight: 800;
            color: #455694 !important;
            text-decoration: solid underline #f5c269;
            text-decoration-thickness: 3px;
        }
    </style>
{% endblock %}

{% block content %}

    <div class="pb-0" id="gallery" style="padding-top: 67px;!important;">
        <div class="container">
            <h2 class="text-center display-5 pb-3 mt-5">Gallery</h2>
            <div class="row portfolio-container gallery-1">
                {% for i in gal_img %}
                    <div class="col-lg-4 mb-4">
                        <figure class="media media-image equal-md-1-1"
                                style="border-radius: 15px 15px 15px 15px"
                                data-bp='{"imgSrc": "{{ i.gallery_img.url }}" , "parentGalleryClass": "gallery-1" }'>
                            <span style="background-image: url('{{ i.gallery_img.url }}')"></span>
                        </figure>
                    </div>
                {% endfor %}
            </div>
        </div>
    </div>

{% endblock %}